"""add todo user-1

Revision ID: 0c14e345366d
Revises: 14686dbd43d4
Create Date: 2023-03-29 21:05:39.250354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c14e345366d'
down_revision = '14686dbd43d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user', sa.String(length=20), nullable=True))
    op.add_column('todo', sa.Column('user_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'user_name')
    op.drop_column('todo', 'user')
    # ### end Alembic commands ###
