"""add todo day completed

Revision ID: 14686dbd43d4
Revises: 9fa4b2fbc726
Create Date: 2023-03-29 20:57:06.361386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14686dbd43d4'
down_revision = '9fa4b2fbc726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('day_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'day_completed')
    # ### end Alembic commands ###
